// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/address.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"` // "BTC", "ETH"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressRequest) Reset() {
	*x = GetAddressRequest{}
	mi := &file_api_proto_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressRequest) ProtoMessage() {}

func (x *GetAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressRequest.ProtoReflect.Descriptor instead.
func (*GetAddressRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_address_proto_rawDescGZIP(), []int{0}
}

func (x *GetAddressRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetAddressRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PathIndex     uint32                 `protobuf:"varint,2,opt,name=path_index,json=pathIndex,proto3" json:"path_index,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressResponse) Reset() {
	*x = GetAddressResponse{}
	mi := &file_api_proto_address_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressResponse) ProtoMessage() {}

func (x *GetAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_address_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressResponse.ProtoReflect.Descriptor instead.
func (*GetAddressResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_address_proto_rawDescGZIP(), []int{1}
}

func (x *GetAddressResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetAddressResponse) GetPathIndex() uint32 {
	if x != nil {
		return x.PathIndex
	}
	return 0
}

func (x *GetAddressResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_api_proto_address_proto protoreflect.FileDescriptor

const file_api_proto_address_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/address.proto\x12\x05proto\"H\n" +
	"\x11GetAddressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"i\n" +
	"\x12GetAddressResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"path_index\x18\x02 \x01(\rR\tpathIndex\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency2S\n" +
	"\x0eAddressService\x12A\n" +
	"\n" +
	"GetAddress\x12\x18.proto.GetAddressRequest\x1a\x19.proto.GetAddressResponseB\n" +
	"Z\b./api/pbb\x06proto3"

var (
	file_api_proto_address_proto_rawDescOnce sync.Once
	file_api_proto_address_proto_rawDescData []byte
)

func file_api_proto_address_proto_rawDescGZIP() []byte {
	file_api_proto_address_proto_rawDescOnce.Do(func() {
		file_api_proto_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_address_proto_rawDesc), len(file_api_proto_address_proto_rawDesc)))
	})
	return file_api_proto_address_proto_rawDescData
}

var file_api_proto_address_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_address_proto_goTypes = []any{
	(*GetAddressRequest)(nil),  // 0: proto.GetAddressRequest
	(*GetAddressResponse)(nil), // 1: proto.GetAddressResponse
}
var file_api_proto_address_proto_depIdxs = []int32{
	0, // 0: proto.AddressService.GetAddress:input_type -> proto.GetAddressRequest
	1, // 1: proto.AddressService.GetAddress:output_type -> proto.GetAddressResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_address_proto_init() }
func file_api_proto_address_proto_init() {
	if File_api_proto_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_address_proto_rawDesc), len(file_api_proto_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_address_proto_goTypes,
		DependencyIndexes: file_api_proto_address_proto_depIdxs,
		MessageInfos:      file_api_proto_address_proto_msgTypes,
	}.Build()
	File_api_proto_address_proto = out.File
	file_api_proto_address_proto_goTypes = nil
	file_api_proto_address_proto_depIdxs = nil
}
